# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Desktop/SCCPU54/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/Desktop/SCCPU54/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files d:/Desktop/SCCPU54/mips_54_mars_board_switch_student_2024.coe
add_files -quiet d:/Desktop/SCCPU54/project_1/project_1.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp
set_property used_in_implementation false [get_files d:/Desktop/SCCPU54/project_1/project_1.srcs/sources_1/ip/dist_mem_gen_0/dist_mem_gen_0.dcp]
read_verilog -library xil_defaultlib {
  D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/sources_1/new/cp0.v
  D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/sources_1/new/divider.v
  D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/sources_1/new/ALU.v
  D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/sources_1/new/RegFile.v
  D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/sources_1/new/CAL.v
  D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/sources_1/new/decoder.v
  D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/sources_1/new/HiLo.v
  D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/sources_1/new/multiplier.v
  D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/sources_1/new/PC.v
  D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/sources_1/new/controller.v
  D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/sources_1/new/cpu.v
  D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/sources_1/new/MEM.v
  D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/sources_1/new/sccomp_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/constrs_1/new/post.xdc
set_property used_in_implementation false [get_files D:/Desktop/SCCPU54/sccpu54/sccpu54.srcs/constrs_1/new/post.xdc]


synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
